### ISSUE TITLE
Tracking Issue Trie Chunk Download

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2003]
In order to download from multiple peers, tries need to be downloadable as chunks by fast-sync.
  - [x] Introduce a chunking hashing scheme with Merkle proofs
  - [x] #2069 
  - [x] Introduce `ChunkWithProof` struct.  It is defined by the following structure:
     ```rust
     pub struct ChunkWithProof {
         proof: IndexedMerkleProof,
         chunk: Vec<u8>,
     }
     pub struct IndexedMerkleProof {
         index: u64,
         count: u64,
         merkle_proof: Vec<Blake2bHash>,
     }
     ```
    Validity condition: the first hash in the Merkle proof must be the same as the Blake2bHash of the data.
     - [x] #2048
     - [x] Only expose smart constructor: `ChunkWithProof::new(index: u64, data: &impl AsRef<[u8]>) -> Result<ChunkWithProof, IndexOutOfBoundesError>`.
     - [x] #2067
     - [x] #2063
  - [x] #2111
  - [x] #2294
  - [x] #2295
  - [x] #2296

**Comment by rafal-ch** [comment]
Validation of deserialization is being reviewed here: https://github.com/xcthulhu/casper-node/pull/7

**Comment by rafal-ch** [comment]
Changes from the following sub-tickets:
#2111 #2067 #2063 #2048 #2069 

are implemented here:
https://github.com/casper-network/casper-node/pull/2119

Further work is blocked by rebase of `fast-sync` to `dev`.

@xcthulhu FYI

**Comment by rafal-ch** [comment]
Merging to `dev` should happen only after https://github.com/casper-network/casper-node/pull/2179 is merged.
