### ISSUE TITLE
Allow Connecting To Network From Behind A NAT

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/casper-node#2058]
Nodes should be able to connect to the network from behind a NAT.

 - [ ] Simplify network interface to use one connection rather than two
 - [ ] Only require open ports for validators (or upcoming)
 - [ ] Enforce that the validator network is complete

**Comment by MParlikar** [comment]
Not going to be in 1.5.0 - it's also too large as written. @Fraser999 please break this up and lets remove from 1.5.0

**Comment by Fraser999** [comment]
I'll break this up when we move the ticket from the backlog.  It will become an epic.

**Comment by devendran-m** [comment]
This will be worked on after 2.0 Release

**Comment by ghost** [comment]
> This will be worked on after 2.0 Release

Could you please assign this to a milestone? https://github.com/casper-network/casper-node/milestones
