### ISSUE TITLE
Account/Contract merge

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#4087]
- [Story]: Get rid of NamedKeys
- https://eips.ethereum.org/EIPS/eip-4337
- https://eips.ethereum.org/EIPS/eip-3074
- [Story]: Fix custom payment code for the account.
   - [Design]: scenario with advance payment ‘voucher’ - signed bytes to be used by another account to pay for the execution.

Notes from recording: https://drive.google.com/drive/folders/1AKLwkk8ZqTbJf29Xglb7x8vAkYoGvddA

Implementation: 
Decision to merge account into contract structure, since contracts are more "dynamic" 
- [x] move account related fields (main_purse, Associated_keys, action_thresholds) to contract structure and remove account structure.  Rebuild and work through compiler issues to identify extensions to contract functionality needed to "backfill" for what was account functionality. Most practical to address crate by crate in this order. 
- [x] Compilation: Casper types crate ('flattening' accounts into contracts)
Note: created a new type called "addressable entity" and preserved account and contract records for historical reasons. 
- [x] Compilation: EE crate, EE test crate
   - account creation --> unified contract creation (13 pts)
   - Locked contracts --> do we still need them? (13 pts)
   - How to handle associated keys? (13 pts)
   - Account hash --> map to contract hash or contract package hash? (13 pts). 
Note: old style account hash --> account; new style account hash [key] --> entity hash (contract hash) [key]--> addressable entity
- [x] On demand: need to handle executing a contract for an account that has not been migrated.  Ex native_transfer in 
Note: a flag is used to signal whether the addressable entity is associated to an account or WASM (contract). Package is created in both creation cases; all account related packages are locked by default (can not be upgraded); 
- [x] Test: Build a network from Genesis and observe, identify and fix runtime errors
    - updates to CI pipeline
    - 
Todo: 

1. **extend action thresholds to support package upgrade access control.** currently key management and deploy.  _upgrade management_ action threshold will be added: Do the approvals have enough weight to upgrade the given package. 21 
2. **stretch goal: rework payment code to allow contracts to pay for themselves.   Can go into a 2.x release.** 
3. **rename the FFI method names: changing the names of the methods within the FFI (runtime string bindings).**   This is where WASM/host exchange takes place. Also removing account specific methods and other methods (record era info) no longer relevant. Adding new methods (get immediate caller).   Underlying types being invoked are renamed making this necessary.   public facing changes an be listed by Fraser's tool (Karan to send info) 
4. overhead: 
- [ ] Update: Casper-Contract Crate [library] - additionally, do we need to update the rust convenience API [contract API] in the casper-contact crate?  Finish the FFI updates first then determine.  21
- [ ] Compilation: Node Crate: RPC changes  [no code change]- documentation will have to be updated to consider the account hash indirection.  

Needs further discussion: 
- separate out contract WASMs in global state.   
- allow packages associated to accounts be updatable? Do we want to allow this.   Initial implementation does not support this (they are locked by default) 
- one more thing???

Migration (TBD): 
gradual transformation:
- [ ] Block creation: as new blocks are produced, gradually move accounts into the new contract representation. 
- CEP-78 --> as part of deploy execution, move the account that sent the deploy into the new structure
- [ ] Can we use empty blocks to speed up transformations? 
- [ ] Test Test Test

Document current and new state

**Comment by devendran-m** [comment]
All the issues under this epic have been completed successfully; therefore, we are closing this epic.
