### ISSUE TITLE
calculate total reward "pot" and distribute based on finality signatures

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-node#4219]
8.18.23
As for now, the plan is that we will compute everything upfront in the node, and send a map of PublicKey -> U512 to the step function, to distribute them (mint & transfer). As I see things we may split that task that way:

We need the total supply to compute the "reward pots". We will:
- [x]  2. We don't have any historical validator data, which is used to compute the signature rewards of past eras. We need to figure out a way to retrieve historical validator data.
- [x]  3. Rollback of the reward code to use the per-era distribution mechanism again, like in dev.
- [ ]  4. Implement the formula to distribute the reward pot (calculated in step 1), based on signatures (retrieved in step 2) in the step function: [here](https://drive.google.com/file/d/1EldXEYcZR2cBLerOjSkWUJkK-CLa_atC/view?usp=drive_link)

**Comment by AlexanderLimonov** [comment]
Feature complete and passing end to end tests
